vistas_path: /your/path/data

labels:
  animal--bird: x
  animal--ground-animal: x
  construction--barrier--ambiguous: x
  construction--barrier--concrete-block: x
  construction--barrier--curb: x
  construction--barrier--fence: x
  construction--barrier--guard-rail: x
  construction--barrier--other-barrier: x
  construction--barrier--road-median: x
  construction--barrier--road-side: x
  construction--barrier--separator: x
  construction--barrier--temporary: x
  construction--barrier--wall: x
  construction--flat--bike-lane: x
  construction--flat--crosswalk-plain: x
  construction--flat--curb-cut: x
  construction--flat--driveway: x
  construction--flat--parking: x
  construction--flat--parking-aisle: x
  construction--flat--pedestrian-area: x
  construction--flat--rail-track: x
  construction--flat--road: x
  construction--flat--road-shoulder: x
  construction--flat--service-lane: x
  construction--flat--sidewalk: x
  construction--flat--traffic-island: x
  construction--structure--bridge: x
  construction--structure--building: x
  construction--structure--garage: x
  construction--structure--tunnel: x
  human--person--individual: 1
  human--person--person-group: x
  human--rider--bicyclist: 2
  human--rider--motorcyclist: 3
  human--rider--other-rider: 3
  marking--continuous--dashed: x
  marking--continuous--solid: x
  marking--continuous--zigzag: x
  marking--discrete--ambiguous: x
  marking--discrete--arrow--left: x
  marking--discrete--arrow--other: x
  marking--discrete--arrow--right: x
  marking--discrete--arrow--split-left-or-straight: x
  marking--discrete--arrow--split-right-or-straight: x
  marking--discrete--arrow--straight: x
  marking--discrete--crosswalk-zebra: 0
  marking--discrete--give-way-row: x
  marking--discrete--give-way-single: x
  marking--discrete--hatched--chevron: x
  marking--discrete--hatched--diagonal: x
  marking--discrete--other-marking: x
  marking--discrete--stop-line: x
  marking--discrete--symbol--bicycle: x
  marking--discrete--symbol--other: x
  marking--discrete--text: x
  marking-only--continuous--dashed: x
  marking-only--discrete--crosswalk-zebra: 0
  marking-only--discrete--other-marking: x
  marking-only--discrete--text: x
  nature--mountain: x
  nature--sand: x
  nature--sky: x
  nature--snow: x
  nature--terrain: x
  nature--vegetation: x
  nature--water: x
  object--banner: x
  object--bench: 4
  object--bike-rack: x
  object--catch-basin: x
  object--cctv-camera: x
  object--fire-hydrant: x
  object--junction-box: x
  object--mailbox: x
  object--manhole: x
  object--parking-meter: x
  object--phone-booth: x
  object--pothole: x
  object--sign--advertisement: x
  object--sign--ambiguous: x
  object--sign--back: x
  object--sign--information: x
  object--sign--other: x
  object--sign--store: x
  object--street-light: x
  object--support--pole: x
  object--support--pole-group: x
  object--support--traffic-sign-frame: x
  object--support--utility-pole: x
  object--traffic-cone: x
  object--traffic-light--general-single: 5
  object--traffic-light--pedestrians: 5
  object--traffic-light--general-upright: 5
  object--traffic-light--general-horizontal: 5
  object--traffic-light--cyclists: 5
  object--traffic-light--other: 5
  object--traffic-sign--ambiguous: x
  object--traffic-sign--back: x
  object--traffic-sign--direction-back: x
  object--traffic-sign--direction-front: x
  object--traffic-sign--front: x
  object--traffic-sign--information-parking: x
  object--traffic-sign--temporary-back: x
  object--traffic-sign--temporary-front: x
  object--trash-can: x
  object--vehicle--bicycle: 6
  object--vehicle--boat: x
  object--vehicle--bus: 7
  object--vehicle--car: 8
  object--vehicle--caravan: 8
  object--vehicle--motorcycle: 9
  object--vehicle--on-rails: 10
  object--vehicle--other-vehicle: 10
  object--vehicle--trailer: 11
  object--vehicle--truck: 11
  object--vehicle--vehicle-group: x
  object--vehicle--wheeled-slow: 10
  object--water-valve: x
  void--car-mount: x
  void--dynamic: x
  void--ego-vehicle: x
  void--ground: x
  void--static: x
  void--unlabeled: x

relabels:
  0: crosswalk
  1: person
  2: bicyclist
  3: motorcyclist
  4: bench
  5: traffic_light
  6: bike
  7: bus
  8: car
  9: motorcycle
  10: vehicle
  11: truck
